### ISSUE TITLE
Create hello world python template

### ISSUE THREAD

**Issue by vineetbansal** [vineetbansal/wbi#11]
After modifying the hello template to only use bash and getting it to work, we then need to create a working python version of it,  (say `pyhello`), but something that activates a custom environment on the cluster.

```
import cowsay
cowsay.cow("hello")
```

For this to work, we need to make `conda activate /tigress/LEIFER/path/to/conda/env` work (i.e. some shared conda env path that has cowsay preinstalled).

This will be a good issue to tackle before issue #10.

The real validation of this would be if someone other than you (who has read/execute permissions on `tigress/LEIFER/path/to/conda/env`) can `pip install wbi` and run `wbi remote pyhello`, and it "just works".

**Comment by anushka255** [comment]
Created a working python version of the `hello` template - `pyhello`. Simultaneously created a similar `pyhello` command. 

- Created a conda environment inside the `tigress/LEIFER/communalCode` directory using the `tigress/LEIFER/communalCode/wbi` prefix
- Installed the `cowsay` package inside the conda environment 
- Loaded the `/anaconda3/2023.9` module by `module load anaconda3/2023.9`
- Activated the conda environment by `conda activate /tigress/LEIFER/communalCode/wib`
- Successfully ran the python interpreter using `python -c "import socket; import cowsay; cowsay.cow('Hello ' + socket.gethostname());"`

**Comment by vineetbansal** [comment]
Great..I'd be interested to try this out if you can open a PR.

I don't think we should add a `pyhello` command though, unless you meant a `wbi remote pyhello`. The latter may work automatically if the template is found (I forgot how we programmed this) and we may not need to do anything.

**Comment by anushka255** [comment]
I created both `wbi remote pyhello` and `wbi pyhello`. I removed the `pyhello` command now and opened a Pull Request.
