### ISSUE TITLE
Move all test data to a common folder in Dropbox

### ISSUE THREAD

**Issue by vineetbansal** [vineetbansal/wbi#34]
The folder structure of files used for testing from Dropbox should mimic what we would use locally, otherwise we're in for a lot of confusion long term.

The URLs used in our `ondemand.py` would have to be regenerated for any moved files of course.

**Comment by anushka255** [comment]
Moved all "expensive" test data to a `wbi_data/long_running_tests/20231024_153302`.

**Comment by vineetbansal** [comment]
Thanks!
