### ISSUE TITLE
Move configuration from pytest.ini to pyproject.toml

### ISSUE THREAD

**Issue by vineetbansal** [vineetbansal/wbi#35]
For projects that have a `pyproject.toml` all tooling configuration information should go in that file, if possible. `pytest` plays well with `pyproject.toml`, so there's no need for a `pytest.ini`.

**Comment by anushka255** [comment]
Removed `pytest.ini` and added all `pytest` configurations in `pyproject.toml`.

**Comment by vineetbansal** [comment]
Thanks!
