### ISSUE TITLE
Convert flash_finder into a wbi command

### ISSUE THREAD

**Issue by anushka255** [vineetbansal/wbi#7]
Right now this is just a script, not a wbi command. We can convert it to a command at some point.

**Comment by anushka255** [comment]
Converted flash finder into a wbi command that takes the following arguments: 
1. input_folder 
2. output_folder 
3. chunk size

Running the command, for example: 
`wbi flash_finder 
--input_folder "/Users/aa9078/documents/Tests/wbi/tests/test_data/" 
--output_folder "/Users/aa9078/documents/Tests/wbi/tests/test_data/" 
--chunksize 1000` 
will run flash_finder on local machine with respective arguments.

**Comment by vineetbansal** [comment]
PR or it didn't happen.
