### ISSUE TITLE
Make hello remote template simpler

### ISSUE THREAD

**Issue by vineetbansal** [vineetbansal/wbi#9]
For `wbi remote` command which uses the `hello.jinja` template, just using `bash` to output `Hello <hostname>` is more robust than using `python` (which is not available on `Della` by default anyway).

**Comment by anushka255** [comment]
Converted previous Python code `python -c "import socket; print('Hello ' + socket.gethostname());"` to a simple bash code `echo "Hello $(hostname)"`.

**Comment by vineetbansal** [comment]
A PR and we can merge this..
